sudo: required
dist: trusty
language: python
python:
  - '2.7'

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo sh -s

install:
  # Copy these states
  - sudo mkdir -p /srv/provision
  - sudo cp -r salt pillar formulas /srv/provision
  - sudo cp .travis/travis_secret.sls /srv/provision/pillar/docker/secret.sls
  - sudo cp salt/minion /etc/salt/minion
  - sudo pip install -U urllib3==1.14
  - sudo service salt-minion restart
  # This ones may fail. So we make sure it returns true.
  - sudo salt-call state.highstate --local --retcode-passthrough || true
  - sudo salt-call state.highstate --local --retcode-passthrough || true

  # Additional debug help
  - sudo cat /var/log/salt/*

  # See what kind of travis box you're on
  # to help with making your states compatible with travis
  - sudo salt-call grains.items --local

script:
  - sudo salt-call state.highstate --local --retcode-passthrough
  # We check if any of the dockers is either halted or restarting, and for each of those we print 'docker logs'.
  - for container in `docker ps -a | grep 'Exit\|Restarting' | awk '{print $NF}'`; do docker logs $container && echo $container; false; done
  - docker ps -a
